# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu"
  #config.vm.network "public_network", ip: "192.168.50.4", bridge: "br-55657f244628"
  config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
    auto_correct: true
  config.vm.usable_port_range = 8000..8999

  # Provider for Docker
  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
  end

  # Provision Docker Engine and pull down PostgreSQL
  config.vm.provision "shell", path: "bootstrap.sh"
end
