# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.box = "mothes/vagrant-provider:ubuntu-jammy"
  config.vm.hostname = "ubuntu"
  for i in 8000..8100
    config.vm.network :forwarded_port, guest: i, host: i
  end
  
  # Provider for Docker
  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "mothes/vagrant-provider:ubuntu-jammy"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup"]
  end

  # Provision Docker Engine and pull down PostgreSQL
  config.vm.provision "shell", path: "bootstrap.sh"
end
